name: Deploy to EC2 instance

on:
  push:
    branches: [ master ]

jobs:
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Start EC2 instance
        run: |
          aws ec2 start-instances --instance-ids ${{ vars.INSTANCE_ID }}
          sleep 40

      - name: Check if instance is ready
        run: |
          echo "public_ip=$(aws ec2 describe-instances --instance-ids ${{ vars.INSTANCE_ID }} --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)" >> $GITHUB_ENV

      - name: Connect via ssh and pull changes
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key
          echo $public_ip
          ssh -i ssh_key ubuntu@$public_ip /bin/bash << EOL
            cd ec2-auto-deploy
            git pull
            npm install
          EOL

      - name: Stop EC2 instance
        run: |
          aws ec2 stop-instances --instance-ids ${{ vars.INSTANCE_ID }}
